convert slice to string only if Marshal is false
projectdiscovery/goflags pull request #22
Opened 2021-08-03 06:21 UTC by parrasajad

fixes #21

2021-08-03 10:15 UTC, forgedhallpass requested changes

2021-08-04 08:38 UTC, Mzack9999 commented on goflags_test.go
> +   -slice-with-default-value string[]          String slice flag with default example values (default [a b c])
Done

2021-08-04 08:39 UTC, Mzack9999 approved these changes

2021-08-04 10:07 UTC, forgedhallpass approved these changes

2021-08-06 06:52 UTC, merged