Add StringSliceVarConfigOnly to handle config only values
projectdiscovery/goflags pull request #33
Opened 2022-01-12 11:41 UTC by parrasajad

2022-01-17 09:54 UTC, forgedhallpass requested changes
Since multiple projects rely on this library, and you've introduced a new functionality/refactored existing code, please make sure to validate your logic by writing tests!

2022-01-26 09:31 UTC, forgedhallpass requested changes

2022-01-26 09:31 UTC, forgedhallpass commented on goflags_test.go
> +	cmd := exec.Command(os.Args[0], "-test.run=TestConfigOnlyDataTypesNegative")
Why do we need this? We should find a better/reusable solution for running the tests.

2022-02-07 10:26 UTC, Mzack9999 approved these changes

2022-02-08 06:37 UTC, Mzack9999 commented
Merging as already used in nuclei `main/dev`

2022-02-08 06:37 UTC, merged