Flag help improvements
projectdiscovery/goflags pull request #78
Opened 2022-09-19 06:38 UTC by parrasajad

2022-10-25 19:06 UTC, ehsandeep requested changes
@parrasajad as of now we can keep this limited to `app --help flagName` and remove the `app --help search` part.

2022-10-27 19:17 UTC, ehsandeep requested changes
- Merge conflict
- Linting error

2022-10-29 00:23 UTC, ehsandeep approved these changes

2022-10-30 06:43 UTC, Mzack9999 approved these changes
lgtm - limited to the first literal match

2022-10-30 10:40 UTC, merged